name: Build charm

on: 
#  pull_request:
  workflow_call:
  workflow_dispatch:

jobs:
  get-runner-image:
    name: Get runner image
    uses: canonical/operator-workflows/.github/workflows/get_runner_image.yaml@main
  build-charm:
    name: Build the charm
    needs: get-runner-image
    runs-on: ${{ needs.get-runner-image.outputs.runs-on }}
    steps:
      - uses: actions/checkout@v3
      - name: Enable network in LXD
        run: sudo iptables -I DOCKER-USER -j ACCEPT
      - name: Add user to lxd group
        run: sudo adduser runner lxd
      - name: Initialize LXD
        run: sudo -u runner lxd init --auto
      - name: Install charmcraft
        run: sudo snap install charmcraft --classic
      - name: Pack charm
        run: sudo -u runner charmcraft pack
      - uses: actions/upload-artifact@v3
        with:
          name: github-runner-charm
          path: github-runner_*.charm
          retention-days: 5
